remote_theme: pages-themes/hacker@v0.2.0

# Setup
title:               'ENG 470 Demo Site'
tagline:             
description:         'A resource for DH Capstone students'
url:                 
baseurl:             
